### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by nmeylan** [nmeylan/RORganize#1]
- [x] Better presentation for permissions
- [x] Add comments count in issues list
- [x] Notifications : emails and in app
 - [x] Send email on modification
 - [x] Introduce watchers
 - [x] Introduce notifications preferences
 - [x] Make better templates.
 - [x] Add in app notifications.
 - [x] Clean notification manager code.
 - [x] Send a single email on bulk edition.
 - [ ] Don't send attachment when size > 2mb.
- [x] Refactor bulk edition / deletion
 - [x] use raw sql instead of AR methods
 - [x] plug all callback with the new system
 - [x] clean up all this stuff
- [ ] Add journals for attachments addition, text modification
 - [ ] Add a text differ
- [ ] Prepare rails 4.2 : [config](http://www.justinweiss.com/blog/2014/08/25/the-lesser-known-features-in-rails-4-dot-2/?utm_content=buffera6b12&utm_medium=social&utm_source=twitter.com&utm_campaign=buffer "prepare")

**Comment by nmeylan** [comment]
- [ ] Models that belong to **Project** should all verify the constraint **project_id presence: true**
- [ ] Generate User **slug** based on **login** instead of **name**
 - [ ] User **name uniqueness** constraint should be remove
