### ISSUE TITLE
Todo release 1.1 (Responsive Design)

### ISSUE THREAD

**Issue by nmeylan** [nmeylan/RORganize#3]
Release 1.1 will make RORganize Responsive.
To reach this target, design will be refactor and now using Bootstrap.
In addition, forms will be refactor to make them more simple with the gem `simple_form`.
- [x] Refactor javascript way of binding (replace js.erb with a binding system based on scope)
- [x] Refactor forms with simple form
- [ ] Refactor all handmade css with bootstrap
  - [ ] Clean css files mess..
    - [ ] Turn `scss` files into `sass` files
  - [ ] Use navbar component
  - [x] Use modal component
  - [x] Use button group 
  - [ ] Use dropdown
  - [x] Use navtab
  - [ ] Use grid
  - [x] Use collapse
  - [x] Use tooltip
  - [x] Use progressbar
  - [ ] Responsive sidebar
  - [ ] Add font-awesome
  - [ ] more...
- [ ] Change look and feel

This release, I hope, will allow to change RORganize style more easily.
